---

- name: Provision development server
  hosts: all

  tasks:
    - include: tasks/update_system.yml
    - include: tasks/install_system_tools.yml
    - include: tasks/install_dev_tools.yml
    - include: tasks/install_postgresql.yml pg_version=9.4
    - include: tasks/install_nginx.yml
    - include: tasks/install_python.yml

  handlers:
    - include: handlers/postgresql.yml