---

- name: Install development tools
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git-core
    - libfreetype6-dev
    - libjpeg8-dev
    - libpng12-dev
    - libyaml-dev
    - libxml2-dev
  become: yes
