---

- name: Import Docker repository key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add Docker repository
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge' state=present
  become: yes

- name: Install Docker
  apt: pkg={{ item }} state=latest
  with_items:
    - docker-ce
  become: yes

- name: Setup Docker user group
  user:
    name: docker
    group: docker
  become: yes

- name: Add current user to docker group to use docker without sudo
  user:
    name: ubuntu
    groups: docker
  become: yes
