---

- name: Install Python and related stuff
  apt: pkg={{ item }} state=latest
  with_items:
    - python2.7-dev
    - python3.5-dev
    - python-setuptools
    - python3-setuptools
    - python-pip
    - python3-pip
    - python-fabric
    - python-virtualenv
  become: yes
